project_name: amazon-item
release:
  github:
    owner: spiegel-im-spiegel
    name: amazon-item

builds:
-
  env:
  - GO111MODULE=on
  goos:
  - linux
  - darwin
  - windows
  - freebsd
  goarch:
  - amd64
  - "386"
  - arm
  - arm64
  goarm:
  - "6"
  main: ./
  ldflags: -s -w -X github.com/spiegel-im-spiegel/amazon-item/product.Version={{ .Version }}
  binary: amazon-item

archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    amd64: 64bit
    386: 32bit
    arm: ARM
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows
    freebsd: FreeBSD
  files:
  - LICENSE*
  - README*
  - template/*

changelog:
  sort: asc
  filters:
    exclude:
      - docs
      - typo
      - Merge pull request
      - Merge branch

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
